# Generated by Django 5.1.1 on 2025-06-27 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_generatedaudio'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='generatedaudio',
            name='page',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='hello.audiopage'),
            preserve_default=False,
        ),
    ]
