# Generated by Django 5.1.1 on 2025-06-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_audiopage_generatedaudio_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedaudio',
            name='pitch',
            field=models.CharField(default='0%', max_length=50),
        ),
        migrations.AddField(
            model_name='generatedaudio',
            name='rate',
            field=models.CharField(default='0%', max_length=50),
        ),
        migrations.AddField(
            model_name='generatedaudio',
            name='style',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generatedaudio',
            name='voice',
            field=models.CharField(default='en-US-JennyNeural', max_length=100),
        ),
    ]
