# Generated by Django 5.1.1 on 2025-06-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_generatedaudio_pitch_generatedaudio_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedaudio',
            name='volume',
            field=models.CharField(default='default', max_length=20),
        ),
    ]
