# Generated by Django 5.1.1 on 2025-06-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_generatedaudio_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedaudio',
            name='pitch',
            field=models.CharField(blank=True, default='0%', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='generatedaudio',
            name='rate',
            field=models.CharField(blank=True, default='0%', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='generatedaudio',
            name='volume',
            field=models.CharField(blank=True, default='default', max_length=20, null=True),
        ),
    ]
