# Generated by Django 5.1.1 on 2025-06-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_alter_generatedaudio_pitch_alter_generatedaudio_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiopage',
            name='default_voice',
            field=models.CharField(default='en-US-JennyNeural', max_length=100),
        ),
    ]
