# Generated by Django 5.1.1 on 2025-06-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_audiopage_default_voice'),
    ]

    operations = [
        migrations.CreateModel(
            name='AzureVoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=100, unique=True)),
                ('locale', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('style_list', models.TextField(blank=True)),
            ],
        ),
    ]
