# Generated by Django 5.1.1 on 2025-06-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0011_loginaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
    ]
