# Generated by Django 5.1.1 on 2025-07-01 19:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0014_favoritevoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_news_bar', models.BooleanField(default=True)),
                ('news_text', models.TextField(default='🔊 This is a totally free Text-to-Audio tool. Contact support@melticetechnology.com for professional tools.')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('show_days', models.PositiveIntegerField(default=30)),
            ],
        ),
    ]
