# Generated by Django 5.1.1 on 2025-07-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0015_sitesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='scroll_direction',
            field=models.CharField(choices=[('left', 'Right to Left'), ('right', 'Left to Right')], default='right', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='scroll_speed',
            field=models.PositiveIntegerField(default=20, help_text='Time (in seconds) for one full scroll loop.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='show_close_button',
            field=models.BooleanField(default=True),
        ),
    ]
